version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ./db.env
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog"]
      interval: 20s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: gsm
    ports:
      - "8080:8080"
    env_file:
      - ./server.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data: